### PR TITLE
Added upcoming and memories filtering

### PR DESCRIPTION
**Pull request by br3sc4**
We also fixed the iCloud video issue that it wasn't playing

### CODE REVIEW

**Comment by bestler** [comment]
For me the whole saving process is not working. But I think that is because of the account.

**Comment by br3sc4** [comment]
> For me the whole saving process is not working. But I think that is because of the account. 

What do you mean?

**Comment by bestler** [comment]
When I add a new Memory and try to save it, it's not working and get this error "error add Account temporarily unavailable due to bad or missing auth token"

**Comment by br3sc4** [comment]
> When I add a new Memory and try to save it, it's not working and get this error "error add Account temporarily unavailable due to bad or missing auth token"

Ah maybe yeah it's because you don't have Nicola's account

**Review by bestler — APPROVED** [review]

**Pull request merged**
